name: setup-aseprite-cli-action
description: GitHub Action to build and install the Aseprite CLI.
branding:
  icon: terminal
  color: white
runs:
  using: composite
  steps:
  - id: prepare
    run: bash ./prepare.sh
    shell: bash
  - id: cache
    uses: actions/cache@v3
    with:
      path: aseprite/build/bin
      key: ${{ runner.os }}-aseprite-v1.3-rc2
  - run: bash ./build.sh
    shell: bash
    working-directory: aseprite
  - run: bash ./install.sh
    shell: bash
    working-directory: aseprite
